### ISSUE TITLE
Automatically define DISABLESTEAMWORKS when running on non-Steam platforms

### ISSUE THREAD

**Issue by fredsa** [rlabrecque/Steamworks.NET#126]
Thanks for the `DISABLESTEAMWORKS` define in c303806e73cc1696775ea36ff8268a59afd6392d.

I think it would be nice if `DISABLESTEAMWORKS` where automatically defined on non-Steam platforms, such as Android/iOS.

Could be as easy as:

```
#if !UNITY_STANDALONE
  #define DISABLESTEAMWORKS 
#endif
```

**Comment by rlabrecque** [comment]
So I was about to do this but the reason why I didn't is that it would remove the symbols from usage elsewhere. I.E. You would need to wrap all steam calls with "#if UNITY_STANDALONE" as well instead of just an if(). Which while it is good practice it would inconvenience a lot of people currently.

Correct me if I'm wrong about that!

**Comment by fredsa** [comment]
I've been thinking about this some more, and realize it probably makes sense to to support both runtime and compile time conditionals.

Perhaps the answer here is to explicitly document how one would remove all Steamworks.NET APIs at compile time, i.e. wherever the docs cover `DISABLESTEAMWORKS` just include an example like:
    #if !UNITY_STANDALONE
      #define DISABLESTEAMWORKS 
    #endif

**Comment by Chaser324** [comment]
This is a nice idea, but if you're on a large project that spans many different platforms, you should probably already have some sort of build automation solution that can handle conditionally defining `DISABLESTEAMWORKS` where it's necessary.

**Comment by andrewspalato** [comment]
Adding DISABLESTEAMWORKS does not work when added to the scripting define symbols.
