### ISSUE TITLE
Steamworks DLLs reimported all the time (Unity 5.5)

### ISSUE THREAD

**Issue by eintopf** [rlabrecque/Steamworks.NET#134]
Hi,

after the import of the current Steamworks.NET the respective Plugin DLLs get reimported on every(!) script change which is quite annoying and slowing down the overal development process. The strange thing is that it really only reimports the Steamworks related dlls, not the other plugin-dlls. Is it possible that some script modifies the .dlls (at least some timestamp or something)? Any one else having this issue?

Best regards
Bennet

**Comment by rlabrecque** [comment]
Hey @eintopf, could you try commenting out line 2 here:
https://github.com/rlabrecque/Steamworks.NET/blob/master/Editor/Steamworks.NET/RedistInstall.cs
Does that help?

**Comment by eintopf** [comment]
@rlabrecque This fixed the issue for the moment. Which side effects can be expected by disabling this redistinstall?

I'll create a pull request for this shortly, since we just need a check that it reimports when really something was modiefied, right? (so GetCompatible before SetCompatible + a check for Reimport)

**Comment by eintopf** [comment]
Ok, this is not as easy as I thought - I think the problem mainly is the "clear settings" call in ResetPluginSettings (since it is only applied in 5.5). Why are you only using it in 5.5?

**Comment by rlabrecque** [comment]
Because it was only introduced in 5.5, given how well this has seemingly been working without it. The theory was that it would just provide us a clean start before we force our preferences on that system.
Honestly I wish none of this code was needed, but Unity broke plugin importing in 5.0 and it no longer sets sensible defaults. Combined with the SetDllDirectory changes in 5.1 this is kind of required now :(

But yeah absolutely create a pull request removing that call (and the lines immediately above/below it and the blank line below that.) I'll accept it as soon as I see it!

**Comment by eintopf** [comment]
Was a bigger change than I thought - the issue was not the ResetPlugin method, it was the usage of the Set-methods without checking if it actually changed. I created a pull request with a potential fix. However: I think this is a bug in Unity, so my change is more or less a workaround.

**Comment by kinifi** [comment]
@rlabrecque lets write up a bug for this on the Unity side and get this handled.
