### ISSUE TITLE
Vote for this stupid Unity issue that causes SW.NET to never allow your game to shutdown from Steam (ADB glitch)

### ISSUE THREAD

**Issue by dylanh724** [rlabrecque/Steamworks.NET#151]
Steam won't shutdown your app until ALL INSTANCES are shutdown. Closing Unity isn't good enough - ADB is a sub process that continues to run in the BG, usually used for Android development. Don't have an Android game? Too bad, it's still running and will cause your game launch to persist through Steam.

This issue is incredibly annoying and directly related to SW.NET - unfortunately, it's a Unity thing. +1 this issue here:

https://issuetracker.unity3d.com/issues/adb-dot-exe-forward-is-executed-despite-build-platform-set-to-standandalone-windows

Best to leave this issue up until Unity resolves the issue so we can keep poking at them.

EDIT: Workaround is `Taskkill /IM adb.exe /F` , can throw it in a batch file or something and click it after shutting down Unity. Anyone know a better way?

EDIT 2: Lazy man's .bat @ https://github.com/Imperium42/killadb

**Comment by fredsa** [comment]
@dylanh724 Thanks for voting up my Unity case as this issue drives me nuts :).

Here are a couple of tips:
- Note you can also run `adb kill-server` to get rid of that adb process.
- As a workaround you can run `adb forward tcp:7201 tcp:7201` *before* starting Unity, which makes it so that Steam will no longer consider adb a subprocess (because it's not spawned from Unity editor).

The more general problem is discussed in issue #13, with a link to Unity case 865265 in this comment: https://github.com/rlabrecque/Steamworks.NET/issues/13#issuecomment-269378363

**Comment by rlabrecque** [comment]
I guess this is fixed in 2017.1? 🎉

**Comment by stonstad** [comment]
> I guess this is fixed in 2017.1? 🎉

Don't believe so.
