### ISSUE TITLE
Question about lobbies

### ISSUE THREAD

**Issue by Crumbler** [rlabrecque/Steamworks.NET#157]
I've thought of a little question. Let's say we have a steamworks lobby with 3 or more people in it. One of them is set as the owner of the lobby. If the owner leaves the lobby, which one of the remaining people becomes the owner?

**Comment by rlabrecque** [comment]
Hey @Crumbler, sorry I missed this! Steam automatically selects the lobby owner on the server side. It's something trivial like the first person that joined, or the lowest Steam ID. It's not something that you should rely on though. If you want to do something a little more advanced, you could have the player that's leaving send a message to change the lobby owner first, and then leave. It might not always work correctly due to packet delays though.
