### ISSUE TITLE
Steam overlay not working on 64 bit / universal OSX builds

### ISSUE THREAD

**Issue by BernsteinA** [rlabrecque/Steamworks.NET#163]
Maybe this is a duplicate of #162, but from my understanding this _should_ be working.
Overlay is working in mac x86 builds, but not x86_64 or Universal.

Same thing happens to me with both https://github.com/rlabrecque/Steamworks.NET-Example and https://github.com/rlabrecque/Steamworks.NET-Test

Am I missing something?

OSX 10.12.5
Unity Editor 5.6.0f3

**Comment by rlabrecque** [comment]
Hey @BernsteinA Yeah, that definitely should be working. I hardly test on macOS because I don't have my own mac, but when ever I did I'm pretty sure I only ever used Universal.

That being said can you report this on the Steamworks developer discussion board? Unfortunately there isn't anything that I can do about the overlay. It's automatically injected on Steams side, whether you have any Steamworks integration or not.

**Comment by BernsteinA** [comment]
I have indeed replicated this issue on an empty Unity project without any integration.

**Comment by hadesfury** [comment]
@BernsteinA did you test it on the last update of Steamworks.NET ? Changelist 65de793c51e4680df3f51b314056f7f422f59bcf

**Comment by BernsteinA** [comment]
@hadesfury yes, but as per above the issue exists even without Steamworks.NET, so it's either a Unity problem or a Steam problem.

**Comment by hadesfury** [comment]
can you link your steamworks post if any?

**Comment by BernsteinA** [comment]
https://steamcommunity.com/groups/steamworks/discussions/0/1291817208491627236/

**Comment by BernsteinA** [comment]
Confirmed: This has nothing to do with Steamworks.NET. Steam overlay does not support Metal.
