### ISSUE TITLE
P2P as Complete Networking Solution

### ISSUE THREAD

**Issue by Cosmas47** [rlabrecque/Steamworks.NET#166]
Besides the GameServer-Test project, are there any other example projects or classes where P2P has been leveraged as a complete networking solution? I'm considering the functionality and ease of implementation of P2P vs. Unet/3rdParty Networking Solution + Steamworks.Net Matchmaking. My game design is such that either P2P or Authoritative could be used, doesn't really matter however P2P sounds attractive if only for the reason that I don't need purchase server hosting.

**Comment by rlabrecque** [comment]
Doesn't UNET and other 3rd party Unity networking packages also support P2P?

It really depends on your current situation, The Steam P2P networking API is heavily stress tested, used in hundreds of huge games (including all of Valve's most recent games and games like Borderlands 2), that being said it is a pretty bare metal solution. It' pretty much only provides 2 functions, one to send data, and  one to receive. You have to build everything yourself on top of it, which is something that the other Unity solutions do already for you.

The Steam P2P networking API also locks you into Steam to some degree, which can be a good thing in terms of piracy etc, but may also hinder you elsewhere. I'd personally use the Steam P2P stuff with a layer similar to the old Unity networking API, but i'm a little biased.

Starting with some real basic packet sending like a heartbeat/checking ping is the best place to start, then maybe getting some kind of RPC calls going, and then basic character position replication going. You'll likely want to read the gafferongames blog before doing any of this.

I'm going to go ahead and close this though since the Steamworks Dev discussions are probably a better place for this.

**Comment by Alloc86** [comment]
Are you sure that the P2P API is really used by Valve titles and Borderlands? I always had the impression they only use the authentication and GameServer APIs, not the P2P networking?
(Just curious as it sometimes felt that it wasn't really 100% done and working yet ;) )

**Comment by rlabrecque** [comment]
Depends on the title, but it's definitely moving that way. You can actually see some of it in the Steam console by using the 'log_ipc' command. The thing with the GameServer API is that it doesn't really do networking, at least anymore. It really just sets up the connection and does some additional work like providing authentication etc. You still need to send the data back and forth with that, in the same way that you need to if you're using say Matchmaking/Lobbies.

I might actually be wrong about BL2 though. I just remember Steam going down and getting booted from the game back in the day, so they definitely had pretty deep integration in some way, could have just been the lobby going down or what ever though. (In which case you should just keep trying to reform the lobby and invite everyone back into it instead of ditching the whole play session!)

**Comment by Alloc86** [comment]
The game kicking you is/can be the authentication API. The server gets callbacks saying that the AuthTicket was canceled and Valve recommends to kick players at that moment (we do too).

I know the GameServer API is only for server lists, just meant I do know those are used e.g. with the Source games. I just always was under the impression (could be wrong though) that they used regular server-based networking protocols for the actual connections. Should really give that IPC logging another try, last time I wanted to get any information out of it I wasn't happy (but that could have been Steam on Linux issues or something ;) ).

**Comment by rlabrecque** [comment]
Indeed! I think BL2 also used Steam Voice though too, it had pretty deep integration in general.
