### ISSUE TITLE
Steamworks is not initialized when calling SteamGameServer.InitGameServer()

### ISSUE THREAD

**Issue by SemihParlayan** [rlabrecque/Steamworks.NET#169]
If I understand it correctly I need to have a game server when trying to create a game using P2P. When I try to initialize a game server using "SteamGameServer.InitGameServer(...)" I get this error:

_InvalidOperationException: Steamworks is not initialized.
_Steamworks.InteropHelp.TestIfAvailableGameServer () (at Assets/Plugins/Steamworks.NET/InteropHelp.cs:31)
Steamworks.SteamGameServer.InitGameServer (UInt32 unIP, UInt16 usGamePort, UInt16 usQueryPort, UInt32 unFlags, AppId_t nGameAppId, System.String pchVersionString) (at Assets/Plugins/Steamworks.NET/autogen/isteamgameserver.cs:21)__

I've googled around and I have not found any solution to the problem. What am I doing wrong?
I'm making sure to check that the SteamManager is initialized properly before trying to create a game server. I can access my persona name and even send P2P packages correctly, it seems like Steamworks should be initialized but I do get this error anyway.

**Comment by rlabrecque** [comment]
Hey @SemihParlayan, I don't think that specific function should actually even be exposed in the API, I'm pretty sure you're supposed to call GameServer.Init() which calls that internally after setting some stuff up. Try that out and let me know how it goes.

**Comment by SemihParlayan** [comment]
Hey @rlabrecque , GameServer.Init worked better but I still do not seem to get any callbacks for these two:
    _private CallResult<P2PSessionRequest_t> OnP2PSessionRequestCallback;
    private CallResult<P2PSessionConnectFail_t> OnP2PSessionConnectFailCallback;_

I have set them up in my OnEnable method like this:
_OnP2PSessionRequestCallback=CallResult<P2PSessionRequest_t>.Create(OnP2PSessionRequest);
OnP2PSessionConnectFailCallback=CallResult<P2PSessionConnectFail_t>.Create(OnP2PSessionConnectFail);_

I have managed to get other callbacks such as creating and entering a lobby. But with those I assigned a handle to the callback. Like this:
_SteamAPICall_t handle = SteamMatchmaking.CreateLobby(ELobbyType.k_ELobbyTypeFriendsOnly, 4);
OnLobbyCreatedCallback.Set(handle);_

What am I missing?
When is the P2P callbacks actually supposed to be triggered? I'm sending a reliable p2p package in hope for the callback to trigger.
Do I need to set a handle for the P2P callbacks aswell and if so, how?

Thanks in advance!

**Comment by yaakov-h** [comment]
@SemihParlayan CallResult<T>.CreateGameServer(…)?

**Comment by SemihParlayan** [comment]
@yaakov-h I can't seem to find the method you are describing.

**Comment by yaakov-h** [comment]
@SemihParlayan https://github.com/rlabrecque/Steamworks.NET/blob/832e0e0861cfb2f96ed293e385627e23ca26e11f/Plugins/Steamworks.NET/CallbackDispatcher.cs#L88

**Comment by SemihParlayan** [comment]
@yaakov-h What is the difference between Callback and CallResult?

**Comment by rlabrecque** [comment]
The difference between SteamNetworking and in SteamGameServerNetworking are just that they are using different underlying versions of the same interface. When you use something like SteamAPI.Init it creates a new underlying steam user type, and then GameServer.Init does the same. After initializing one only supposed to use either the regular interfaces or the SteamGameServer* interfaces with that user, Steamworks .NET abstracts this away a little bit because it's just a lot of pointer management under the hood. Things get a little muddier when you have both a regular user and a game server at the same time, and you shouldn't really need that if you're just wanting to use the P2P stuff.

Callbacks are global event sinks that will get called EVERY time that callback is sent, while CallResults are function specific handlers which only get called after you specifically associate the handler function with the SteamAPICall_t. If a function returns a SteamAPICall_t then it NEEDs a CallResult, otherwise it needs to be a callback, specifically P2PSessionRequest_t and friends are only callbacks, because you're not waiting for a function to return.

All of this should be a little clearer in about a week. :)

**Comment by SemihParlayan** [comment]
Thank you for your answer, I do have some followup questions though.
1. I don't need a GameServer if I'm focusing on P2P?
2. What am I doing wrong with my P2P callbacks, they never get called.
3. "All of this should be a little clearer in about a week. :)" Is there some sort of update coming out regarding P2P?

**Comment by rlabrecque** [comment]
1. Nope! I'd only use them if your game needs them for some reason. Some reasons might be that your game is competitive and you're using dedicated servers, you want your servers to outlast the lobby, etc

You can have the owner of the lobby act as the host, and everyone would send packets right to them using the P2P Networking.

2. I'm pretty sure those need to be Callbacks, not CallResults. (Try to grab your code from https://github.com/rlabrecque/Steamworks.NET-Test , it's what I do when ever I'm doing Steamworks stuff.)

3. Something sort of like that, or at least information that might make it easier to use this stuff. 👍

**Comment by SemihParlayan** [comment]
Thanks alot @rlabrecque  , I managed to get the callbacks correctly and connected two clients without a gameserver. Thanks alot!

**Comment by rlabrecque** [comment]
Will do, and the thing that I was hinting at: http://steamcommunity.com/groups/steamworks/announcements/detail/1334602669405427884

Hopefully it helps out a little!
