### ISSUE TITLE
Mac Build (Universal) - Overlay not functioning

### ISSUE THREAD

**Issue by GLJeff** [rlabrecque/Steamworks.NET#171]
Works fine for PC builds, but there's no overlay on Mac. I don't believe this issue existed using 7.0.0, but does now in 9.1.0

**Comment by GLJeff** [comment]
I believe this is just a Universal build issue, x86 doesn't have it.

**Comment by rlabrecque** [comment]
Hey @GLJeff, I'm going to go ahead and close this based on this thread:
http://steamcommunity.com/groups/steamworks/discussions/0/1291817208491627236/

I'm guessing you updated to Unity 5.6 at the same time as updating Steamworks.NET? :)

Solution: http://steamcommunity.com/groups/steamworks/discussions/0/666827974770212954/?ctp=14#c2333276539598181889

Docs stating lack of Metal support:
https://partner.steamgames.com/doc/features/overlay

**Comment by DavidAbrakam** [comment]
Hello!
Just popping here to say that:
- Unity 2017.3 will **enforce** MacOS 64 bit builds and thus Metal by default (32bit OpenGL will be discontinued). However, Metal can still be disabled on 64 bit MacOS builds by disabling it in the PlayerSettings.
- However, the latest Steam client update contains the entry _Added full support for game engines using the Metal rendering API_! So in fact this issue is not even closed anymore, it is **solved**. I tried it today on a Metal Unity build and I managed to get the steam overlay working (shift+tab). At last, support for Metal on Steam!

I thought you would like to know; to be sure you should retest all your use cases but it seems OK now.
