### ISSUE TITLE
Steamworks cannot find DLL

### ISSUE THREAD

**Issue by beneton** [rlabrecque/Steamworks.NET#19]
Hi there, I'm using Steamworks for my game and it's running on Mac and PC.

Mac version is running fine, but PC version cannot find steam_api.dll.
"[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details."

The error debug tells me that the file should be at the folder: 
GAME_FOLDER/eus_data/Plugins/steam_api.dll

And well... it is there!

I'm running the game from within Steam.

Any help would be great! :)

**Comment by mooseproofgames** [comment]
I recently just just started having this same issue, everything is in place, and it was working before, i updated unity and it worked for a few hours and then just stops loading that dll, iv deleted the asset out of my project and reimported it, nothing seems to be working, everything is in its proper place.

**Comment by DetectiveMittens** [comment]
I am also getting the error "[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: Assets/Plugins/x86_64/CSteamworks.dll
"

I have steam_api.dll in the root folder at the same level as "Assets" folder

**Comment by rlabrecque** [comment]
The issue is that the steam_api.dll must be next to CSteamworks.dll in Assets/Plugins/x86_64/ now as of Unity 5.1.

This is reflected in 7f2747fb05b480e4cdda67fa6275186d9976f286.

**Comment by DetectiveMittens** [comment]
I see, but I already have steam_api.dll and steam_api64.dll in those folders, 
I only pulled the repo from github a few hours ago. 

I am still on unity 5.0 though, I will try upgrading to 5.1 now and see if that fixes it

**Comment by DetectiveMittens** [comment]
Yep, that worked. 
So the current repo just wont work with any version of Unity other than the latest.
All fixed

**Comment by rlabrecque** [comment]
Good to know, I'll get that fixed before making a unitypackage release.

**Comment by akutruff** [comment]
Ugh, I'm pulling my hair out right now.  Our game has been built and is live on Steam.  

I could have sworn SteamWorks was working in the editor last month, and  I'm trying to run in the editor and I keep getting this error. The DLL's are in the plugins folder.  I have tried putting our app id in SteamAPI.RestartAppIfNecessary.  If I remove steam_appid.txt, Steamworks just adds it back.

```
[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: CSteamworks
  at (wrapper managed-to-native) Steamworks.NativeMethods:SteamAPI_RestartAppIfNecessary (Steamworks.AppId_t)
  at Steamworks.SteamAPI.RestartAppIfNecessary (AppId_t unOwnAppID) [0x00005] in C:\code\main\BattleBirds\client\Assets\Plugins\Steamworks.NET\Steam.cs:39 
  at SteamManager.Awake () [0x0006c] in C:\code\main\BattleBirds\client\Assets\Scripts\BaseScene\SteamManager.cs:79 
CSteamworks
UnityEngine.Debug:LogError(Object, Object)
SteamManager:Awake() (at Assets/Scripts/BaseScene/SteamManager.cs:86)
UnityEngine.Object:Instantiate(GameObject)
ApplicationBootLoader:Awake() (at Assets/Scripts/Application/ApplicationBootLoader.cs:12)

```

**Comment by gsylvain2** [comment]
I also have the same issue on Unity 5.3.4f1, target windows - x86.

Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/***/game_Data/Mono/libC:/Program Files (x86)/Steam/steamapps/common/***/game_Data/Plugins/CSteamworks.dll
[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: C:/Program Files (x86)/Steam/steamapps/common/***/game_Data/Plugins/CSteamworks.dll
  at (wrapper managed-to-native) Steamworks.NativeMethods:SteamAPI_RestartAppIfNecessary (Steamworks.AppId_t)
  at Steamworks.SteamAPI.RestartAppIfNecessary (AppId_t unOwnAppID) [0x00000] in <filename unknown>:0 
  at SteamManager.Awake () [0x00000] in <filename unknown>:0

**Comment by nihilocrat** [comment]
Same issue here, exact same DLL is misbehaving, Unity 5.3.4f1, Windows x86 target.

I tried the suggestions in this thread but none seem to work (https://github.com/rlabrecque/Steamworks.NET/issues/83) ... technically the issue here arises before the Init() call anyways.

Oddly enough a different project using 5.2.4 has no problems, even though the DLLs are in the same place and have the same metadata settings. To be honest I'm not certain if it's using an older version of Steamworks.NET though.

**Comment by matej-zajacik** [comment]
Hey guys!

We are having a similar problem. Our [game](http://store.steampowered.com/app/629690/Vaporum/) has been out for several months now, and we never encountered any errors of this sort. This morning, the game started crashing when run from the default (normal public) branch via Steam. I'm getting the same error:

```
[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: CSteamworks
  at (wrapper managed-to-native) Steamworks.NativeMethods:SteamAPI_RestartAppIfNecessary (Steamworks.AppId_t)
  at Steamworks.SteamAPI.RestartAppIfNecessary (AppId_t unOwnAppID) [0x00000] in <filename unknown>:0 
  at SteamManager.Awake () [0x00000] in <filename unknown>:0  
```

We haven't changed a single thing regarding Steamworks.NET; we just checked the version control logs. What's even more bizarre is that I uploaded the same build to both the default branch and our testing branch (retail depot), and it runs 100% okay in the testing branch, but throws the error in the default. Can this be caused by some recent changes in the Steam client itself?

Makes no sense to me why it would stop working all by itself suddenly.

Thank you!
