### ISSUE TITLE
Unable to compile non-Steam targets

### ISSUE THREAD

**Issue by AdriaandeJongh** [rlabrecque/Steamworks.NET#200]
Hey there!

I just updated to the latest version of Steamworks.NET and I'm unable to compile for iOS or Android or any other platform that's not Steam:

- The symbol 'DISABLESTEAMWORKS' is never defined for platforms other than PC / Mac / Linux, which should.
- SteamAPI_PostAPIResultInProcess_t.cs is missing the DISABLESTEAMWORKS checks.

**Comment by rlabrecque** [comment]
Hey @AdriaandeJongh, I think SteamAPI_PostAPIResultInProcess_t.cs got removed at some point because I can't find it. And unfortunately I can't easily define that globally automatically, what you should do instead is set up a "Platform custom #define" as outlined [here](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html) for your non-Steam platforms.

**Comment by AdriaandeJongh** [comment]
Can't you add something like 'if iOS or Android or <platforms>' (or the inverse) then define DISABLESTEAMWORKS? The platform scripting define symbols are really not meant to disable plugins meant for _other_ platforms.

**Comment by rlabrecque** [comment]
Yeah, I've gone ahead and added that! I was just being lazy before, but you're right it should just work out of the box. Now, that being said any usages of Steamworks.NET will have to be wrapped in an ifdef or not included on the platform you're building for still.
Let me know how it works for you with: 34c9ee5a45cdef515cbb206e4eac078b91a062a6
