### ISSUE TITLE
SteamManager.Initialized throws NullReferenceException

### ISSUE THREAD

**Issue by m4ff** [rlabrecque/Steamworks.NET#208]
The _Initialized_ property is currently defined as

`public static bool Initialized
{
    get
    {
        return s_instance.m_bInitialized;
    }
}`

and throws a _NullReferenceException_ if _s_instance_ is _null_. In my game I add the _SteamManager_ component only if launched from Steam. In all other cases _s_instance_ is _null_, but it would still be useful to call _SteamManager.Initialized_ and have it return _false_.

I suggest you slightly change the definition by adding a null check, so that it returns _false_ instead of throwing a _NullReferenceException_.

`public static bool Initialized
{
    get
    {
        return s_instance && s_instance.m_bInitialized;
    }
}`

**Comment by rlabrecque** [comment]
Hmm, I think you're probably better off modifying SteamManager yourself, the reason it gets dumped in Assets/Scripts/ is that it's just the base that you can build from and make your own. I think you might have an older version, because the way it's defined currently is:
`public static bool Initialized { get { return Instance.m_bInitialized; } }`
The `Instance` property is a self creating singleton, so it should never be null.
