### ISSUE TITLE
Steamworks SDK v1.44 support

### ISSUE THREAD

**Issue by KelsamGames** [rlabrecque/Steamworks.NET#272]
Steamworks SDK v1.44 released. Only a couple weeks after v1.43

**Comment by rlabrecque** [comment]
That was quick!

This weekend!

**Comment by rydeom** [comment]
Hey,
when is the new version available? 

rydeom

**Comment by rlabrecque** [comment]
It was harder than anticipated unfortunately and then I was off to GDC, this weekend?!

**Comment by alexcodejammer** [comment]
Hi. Any update available on this?

**Comment by rocktavious** [comment]
I'm interested in this too as i'd like to checkout the new Networking API's announced at GDC 2019.  Thanks for all your effort!

**Comment by chull434** [comment]
Hi. Any update on this?

**Comment by JashanChittesh** [comment]
1.44 seems to be a tough one!? Most likely it's exactly the new networking API that's causing pains.

**Comment by rlabrecque** [comment]
Yeah, it just does things a little differently, lots of big structs to be manually copied over, and I'm in the middle of a move still unfortunately :(

**Comment by sinxtanx** [comment]
[monthly inquiry of status]

**Comment by OndrejPetrzilka** [comment]
I've did some prototyping and I'm able to safely use new networking from Steamworks.NET
1) Used latest Steamworks.NET
2) Updated binaries to 1.44
3) Disabled many interfaces in CSteamAPIContext.Init (they have different versions)
https://gist.github.com/OndrejPetrzilka/7952f42032618952174d41a2360985aa
...these will get updated by your autogen eventually

4) Added few classes for networking and to support "new" way of getting things
https://gist.github.com/OndrejPetrzilka/390ff672de88e47e2a2a8b5d7fb18fb6
https://gist.github.com/OndrejPetrzilka/eb83db3d466b0c5af2e9a6434dec51de
+more files with structs like SteamNetworkingIPAddr or HSteamListenSocket

It should be pretty obvious how to get around things "new way" or just ask here.
I've tested simple scenario: listen on socket, get IP+port of listening socket, close socket (using it in Unity - Windows).

My prototype is highly suboptimal (e.g. loading whole vtable instead of single pointer).
I'll keep working on improving things and implementing all methods of ISteamNetworkingSockets and ISteamNetworkingUtils.

Offtopic:
We have successful product on Steam Early Access and this API is godsend for us, because current Unity networking situation is quite bad (UNET, LLAPI depracated, new com.unity.transport unstable) and we're about to start implementing multiplayer.

**Comment by OndrejPetrzilka** [comment]
I've progressed with implementation, sending and receiving messages is done and tested.

Native interop is now done through cached delegates (steam interfaces are pure abstract classes, delegates are created from their vtable). It still subobtimal, but good enough IMO.

Optimal solution (for performance) might be similar to how SharpDX does native calls:
- it uses calli IL instruction which is fastest way to make native calls
- but requires DLL with at least generated signatures (single portable pure-IL DLL for both x86 and x64)
-- single DLL would probably work for all platforms / ifdefs - it would contain only static methods with calli

At some point I'll probably make fork of this repo so anyone can test SteamNetworkingSockets before official Steamworks.NET version is out. It could also help to speed up the development.

**Comment by OndrejPetrzilka** [comment]
I'm glad Valve added flat interface...it's much simpler and does not require VTable workarounds.
