### ISSUE TITLE
Unity consistently crashing when play button is pressed for second time.

### ISSUE THREAD

**Issue by Ratstail91** [rlabrecque/Steamworks.NET#329]
Project affected: https://github.com/Ratstail91/DecadeDice

I'm also running this non-unity project at the same time: https://github.com/Ratstail91/DecadeDiceServer

I start the game, then enter the lobby screen, then exit. When starting the game again, unity crashes. 

My guess is `SteamMatchmakingServerListResponse` finishes, but doesn't properly release the `HServerListRequest` instance. I've tried everything I can.

**Comment by rlabrecque** [comment]
Hey @Ratstail91, I had a look, it looks like what's happening is primarily lifetime issues with your `SteamMatchmakingServerListResponse` class

https://github.com/Ratstail91/DecadeDice/blob/master/Assets/Scripts/SteamMatchmakingServerListResponse.cs

The Finalizer (~SteamMatchmakingServerListResponse) was a large part of the issue.

But I have put in a couple fixes that I found along the way so that it no longer crashes!

Thanks for the detailed report, I was able to repro it within a few minutes of grabbing that project!

These two should fix the crash:
https://github.com/rlabrecque/Steamworks.NET/commit/a54039e76dd00d6ce475cdad9f943ddf7406f41e

https://github.com/rlabrecque/Steamworks.NET/commit/8a40414b9ee6079ec3334c88c696686c9fe06bd0

But you should check out this example of using these APIs:

https://github.com/rlabrecque/Steamworks.NET-Test/blob/master/Assets/Scripts/SteamMatchmakingServersTest.cs#L18

Unity doesn't play nice with static or finalizers
