### ISSUE TITLE
[macOS] Is it correct that the Steam libs are in the compiled app's Plugins folder twice?

### ISSUE THREAD

**Issue by AdriaandeJongh** [rlabrecque/Steamworks.NET#357]
Hey there! After trying to also make a Mac App Store validatable build of my game, I discovered that there are two Steam libraries in my project, one from the .bundle, and another from the x84_64 folder. Is that correct? It could totally be that I messed up the checkboxes what libs to include in with what plarform. Can someone shed a light on this? Are they both needed?

<img width="622" alt="Screenshot 2020-05-15 at 13 50 49" src="https://user-images.githubusercontent.com/5611323/82047493-32929100-96b3-11ea-8c28-ee9e71452d7d.png">

**Comment by muclem** [comment]
Hello,

It's funny you ask this. I just updated Unity from 2019.3.10f1 to 2019.3.13f1, and now I cannot build on macOS anymore because of this error:

Plugin 'libsteam_api.so' is used from several locations:
 Assets/Plugins/x86_64/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
 Assets/Plugins/x86/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by AdriaandeJongh** [comment]
@muclem it appears that the plugin settings for the Steam libraries are messed up; in Unity, check the import settings on `Assets/Plugins/x86/libsteam_api.so` and make sure it's only copied to 32-bit macOS builds and check `Assets/Plugins/x86_64/libsteam_api.so` is only copied to 64-bit macOS builds. 

I'm personally only making 64-bit builds these days, so I went ahead and removed the `Assets/Plugins/x86/` entirely :)

However, it could totally be that the `.so` libs aren't meant for macOS at all, because there's a `.bundle` lib in the plugin as well? That's why I asked my original question.

**Comment by muclem** [comment]
Hey Adriaan, thanks a lot for your answer, I'll use these settings! I hope you'll get an answer to your question.
(big fan of Hidden Folks, keep up the amazing work ;))

**Comment by jenmakesgames** [comment]
Hello,

I get the same error as @muclem when trying to build on Mac (Windows works fine), but the import settings look correct already:

x86:

![image](https://user-images.githubusercontent.com/47460580/84686011-13498680-af33-11ea-9d21-783974f4252f.png)

x64:

![image](https://user-images.githubusercontent.com/47460580/84686060-2c523780-af33-11ea-8a02-a2e5a52b78bc.png)


Deleting the x86 folder allows me to build the project, but the build then crashes when you play the game: 

```
[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: steam_api
  at (wrapper managed-to-native) Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(Steamworks.AppId_t)
  at Steamworks.SteamAPI.RestartAppIfNecessary (Steamworks.AppId_t unOwnAppID) [0x00005] in <fb63d24cc2a04579a05ee59feb5d4973>:0
  at SteamManager.Awake () [0x00061] in <f41730c93f5941b9a4132b9c391a60e4>:0  
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

The same project works fine on the Windows build. It's only Macs that have a problem.

I've just tried updating to Unity 2019.4.0 just in case the problem was on Unity's end, but I get the same result.

**Comment by MigrantP** [comment]
I just updated our game to 14.0.0 and ran into this. I was able to solve this by unchecking Mac OS X on the x86_64/libsteam_api item. Note you need to do so on the Player tab, not the Editor tab!

**Comment by jenmakesgames** [comment]
Thanks, I did also try that, but the crash still happened. I've now discovered my problem was the version of MacOS - Unity has dropped support for some older versions at some point during the last few months, and that's what was causing the build to crash. It just looked like it was the Steam files because of the exception, but a Mac running Catalina runs the game fine.

**Comment by rlabrecque** [comment]
Just a note for myself or anyone else wanting to look into fixing this:

The issue is likely in here: https://github.com/rlabrecque/Steamworks.NET/blob/master/Editor/Steamworks.NET/RedistInstall.cs

**Comment by buddhisthead** [comment]
@MigrantP  Thanks for the work-around. I'm seeing this issue now that I've moved to Unity 2020. What do you mean by "on the player tab" vs the editor tab? Which "tab" are you referring to? Thanks!

**Comment by MigrantP** [comment]
@buddhisthead You can see in the inspector screenshot above - under Platform settings, there's a tab with the Unity icon (Editor Settings) and one without (Player settings).

**Comment by buddhisthead** [comment]
@MigrantP Thank you! All these years using Unity and I didn't know what those icons mean. I appreciate the tip. Using your earlier suggestion, I turned off libsteam for Macos and deployed a build via steam.
- building from new Apple Silicon Mac, submit to Steam succeeded, but failed to run on all client machines.
- building from old x84-64 Mac, submit to Steam succeeded, and ran correctly on all client machines.

So, the problem would appear to be on the machine that is running the build. It generates a build that does not run on Mac systems (showing a failure in the Player.log file where the steam library can't be loaded, as in my previous comment).

**Comment by buddhisthead** [comment]
The actual problem was that I set the target Architecture to "Intel 64-bit + Apple Silicon" where it should only be set to "Intel 64-bit". With this change, building from my M1 Apple Silicon laptop resulted in success. Detailed notes appear in the following issue comment: https://github.com/rlabrecque/Steamworks.NET/issues/393#issuecomment-764801885

**Comment by rlabrecque** [comment]
This should be resolved on `master` now that we ship the .meta files for Unity and explicitly set this rather than letting Unity set it.

https://github.com/rlabrecque/Steamworks.NET/pull/414
