### ISSUE TITLE
Issue with OSX builds in Unity 2020.2 (steam_api.bundle does not get copied to .app plugins)

### ISSUE THREAD

**Issue by spajus** [rlabrecque/Steamworks.NET#393]
Hey @rlabrecque 

I just spent a few hours to figure out why Unity build crashes on OSX after upgrading Unity to 2020.2.

I suspected it had something to do with `"Plugins"` folder is now being named `"PlugIns"`, but changing that line didn't help (also this would probably fail on case sensitive systems): https://github.com/rlabrecque/Steamworks.NET/blob/14.0.0/Editor/Steamworks.NET/RedistCopy.cs#L67

I would guess it's something in `RedistInstall.cs`, didn't have enough time to poke around it yet, could eventually do that and make a PR, unless you fix it first :)

**Comment by rlabrecque** [comment]
Oh jesus they renamed the Plugins folder..? :/ What problem were they trying to solve? D:

**Comment by spajus** [comment]
I think they just tried to make it follow Apple conventions
![image](https://user-images.githubusercontent.com/70706/103476118-a658e980-4dbb-11eb-8ce0-06d01de9b8ce.png)

**Comment by spajus** [comment]
I dug a bit more, and here's what I found:

1. Need to add UNITY_2017_1_OR_NEWER to defines, otherwise it does not get called at all
https://github.com/rlabrecque/Steamworks.NET/blob/master/Editor/Steamworks.NET/RedistInstall.cs#L27 

2. After RedistInstall does it's thing, platform settings becomes AnyCPU / OSX, but after the build, an override for Mac OS X  with CPU: Intel 64-bit appears in the editor:

![image](https://user-images.githubusercontent.com/70706/103477322-706d3280-4dc6-11eb-9648-7bc98535e19e.png)

Changing this to Any CPU manually solves the issue. Not sure how or why it becomes Intel 64-bit though.

**Comment by TautvydasZilys** [comment]
> Oh jesus they renamed the Plugins folder..? :/ What problem were they trying to solve? D:

I suspect that's an issue in the docs. It wasn't renamed.

**Comment by TautvydasZilys** [comment]
> Oh jesus they renamed the Plugins folder..? :/ What problem were they trying to solve? D:

It was renamed due to https://issuetracker.unity3d.com/issues/macos-code-signing-using-deep-flag-fails-on-built-package-due-to-incorrect-case-in-built-contents-slash-plugins-folder. Apple's notarization tooling didn't work with "Plugins".

**Comment by spajus** [comment]
> If plugin settings change on their own, can we get a Unity bug report on this?

Tried to create a repro project now, and seems there's no issue after all! Documented the process:

Also, here are some logs from fresh import of Steamworks.NET into empty Unity 2020.2.0f1 project:

![image](https://user-images.githubusercontent.com/70706/103850144-3d20f100-50af-11eb-89d3-b6a38713c995.png)

Although it seems that it set everything more or less correctly for steam_api.bundle this time:

![image](https://user-images.githubusercontent.com/70706/103850301-97ba4d00-50af-11eb-8bf9-c0563bd13a19.png)
![image](https://user-images.githubusercontent.com/70706/103850323-a3a60f00-50af-11eb-9bd2-d9567a09e52f.png)

After setting build settings to Intel-64 bit (any chance of making steam_api.bundle native silicon btw?) and trying to build:

```
Plugin 'libsteam_api.so' is used from several locations:
 Assets/Plugins/x86/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
 Assets/Plugins/x86_64/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions (string)
UnityEditorInternal.PluginsHelper:CheckFileCollisions (UnityEditor.BuildTarget)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

Interesting observation, 32-bit libsteam_api.so plugin is set as None for OSX, so I presume the error above should not happen?
![image](https://user-images.githubusercontent.com/70706/103850479-03041f00-50b0-11eb-993c-dbd4f28fc8fb.png)

Now 64-bit libsteam_api.so is set to Intel 64-bit for Mac OS X, I think it should also be None:
![image](https://user-images.githubusercontent.com/70706/103850586-4bbbd800-50b0-11eb-81a3-22010b94745d.png)

Setting 64-bit libsteam_api.so to None for OSX made the build pass.

Fortunately (unfortunately for me)  in a fresh project I got a proper build and steam_api.bundle was copied over correctly, with both "Intel 64-bit + Apple silicon" and "Intel 64-bit" targets.

So looks like it is something in my own build scripts. But I guess it's good news then!

One thing though for @TautvydasZilys - perhaps Unity could validate your plugins when you're trying to make a build with "Intel 64-bit + Apple silicon"? If that's possible. I do believe people will be pushing out builds with default configuration and running into "Open with Rosetta" being unchecked in Steam.

**Comment by TautvydasZilys** [comment]
> Interesting observation, 32-bit libsteam_api.so plugin is set as None for OSX, so I presume the error above should not happen?
image

Looks like a bad error message. I might sound like a broken record, but do you might filing a bug report on that?

> perhaps Unity could validate your plugins when you're trying to make a build with "Intel 64-bit + Apple silicon"? If that's possible. I do believe people will be pushing out builds with default configuration and running into "Open with Rosetta" being unchecked in Steam.

We probably should... We didn't really expect people to ship games without testing them 😄 .

**Comment by spajus** [comment]
> Looks like a bad error message. I might sound like a broken record, but do you might filing a bug report on that?

I already deleted the test project, sorry. Not sure if it's a unity issue actually, Steamworks.NET is doing the plugin setting changes on import.

Also, I already exceeded my time budget I could afford spending on this issue :)

> We probably should... We didn't really expect people to ship games without testing them 😄 .

1. Not everyone has a Mac
2. Not everyone who has a Mac can afford the latest Apple silicon model (me)
3. You can make Mac builds from Windows (which I'm doing)
4. As an indie solo developer with zero budget, there's no choice but to release untested builds like that

So yeah, it's something poor people do.

**Comment by buddhisthead** [comment]
I'm not sure if it's the same issue, but when I run my built app (targeting Mac OS) on my M1 laptop, the app shows the initial splash screen, the first scene, and then quits during the steam api init call. At the suggestion of @rlabrecque I copied the steam_api.bundle to `/Contents/Frameworks/MonoEmbedRuntime/osx/` but that did not solve the problem. I tried copying the `libsteam_api` libraries there as well, with no joy. So, even when the library was located at the exact place where an error message said it couldn't be loaded, it still failed. Which makes me wonder if it's also dependent on an inclusion setting for platform. Any how, I'm stumped; and I can't ship my game on Steam for Mac until I resolve this.

```
System.DllNotFoundException: steam_api
  at (wrapper managed-to-native) Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(Steamworks.AppId_t)
  at Steamworks.SteamAPI.RestartAppIfNecessary (Steamworks.AppId_t unOwnAppID) [0x00005] in <950de3039d884d609b9ba53c954212a3>:0 
  at HeathenEngineering.SteamApi.Foundation.SteamworksFoundationManager.Awake () [0x0009e] in <c98eb06ed4cd4ea6a91028d9051bf47a>:0 

[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: steam_api
  at (wrapper managed-to-native) Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(Steamworks.AppId_t)
  at Steamworks.SteamAPI.RestartAppIfNecessary (Steamworks.AppId_t unOwnAppID) [0x00005] in <950de3039d884d609b9ba53c954212a3>:0 
  at SteamManager.Awake () [0x00061] in <c98eb06ed4cd4ea6a91028d9051bf47a>:0 

Fallback handler could not load library /Users/chris/Personal/Projects/HexMap/HexMapEditor/Builds/Mac/Overworld.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api
Fallback handler could not load library /Users/chris/Personal/Projects/HexMap/HexMapEditor/Builds/Mac/Overworld.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.dylib
Fallback handler could not load library /Users/chris/Personal/Projects/HexMap/HexMapEditor/Builds/Mac/Overworld.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.so
Fallback handler could not load library /Users/chris/Personal/Projects/HexMap/HexMapEditor/Builds/Mac/Overworld.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.bundle
Fallback handler could not load library /Users/chris/Personal/Projects/HexMap/HexMapEditor/Builds/Mac/Overworld.app/Contents/Frameworks/MonoEmbedRuntime/osx/steam_api
Fallback handler could not load library /Users/chris/Personal/Projects/HexMap/HexMapEditor/Builds/Mac/Overworld.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api
Fallback handler could not load library /Users/chris/Personal/Projects/HexMap/HexMapEditor/Builds/Mac/Overworld.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.dylib
Fallback handler could not load library /Users/chris/Personal/Projects/HexMap/HexMapEditor/Builds/Mac/Overworld.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.so
Fallback handler could not load library /Users/chris/Personal/Projects/HexMap/HexMapEditor/Builds/Mac/Overworld.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.bundle
Fallback handler could not load library /Users/chris/Personal/Projects/HexMap/HexMapEditor/Builds/Mac/Overworld.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api
```

**Comment by buddhisthead** [comment]
I'll try repeating the same steps on an Intel64 mac as well.

**Comment by rlabrecque** [comment]
@TautvydasZilys I may want some help with this, as I do believe there's a Unity problem.

Steamworks .NET should not be modifying the settings on Unity 2018 or newer: https://github.com/rlabrecque/Steamworks.NET/blob/master/Editor/Steamworks.NET/RedistInstall.cs#L26-L31

We used to modify the settings because Unity wasn't doing a good job at setting sensible defaults. I believe this may have regressed on one of the following releases: 2019.3.11f1, 2019.3.12f1, 2019.3.13f1 (Worked fine on 2019.3.10f1?)

Given this folder layout: https://github.com/rlabrecque/Steamworks.NET/tree/master/Plugins are there any obvious problems, or should I open a ticket?

Do I need to rename this Plugins folder for the steam_api.bundle copy to work for modern macOS, or does Unity do that automatically?

Current problems:

1. macOS Plugins -> PlugIns change causes steam_api.bundle not to get copied.
2. Plugins/x86_64/libsteam_api.so gets incorrectly copied on macOS, possibly causes a conflict with steam_api.bundle.
3. Building from an Apple Silicon Mac results in a broken build (unknown why as of yet).

Related issues:
https://github.com/rlabrecque/Steamworks.NET/issues/344
https://github.com/rlabrecque/Steamworks.NET/issues/357

**Comment by spajus** [comment]
> macOS Plugins -> PlugIns change causes steam_api.bundle not to get copied.

I believe it's actually the new default build target (intel64 + silicon) that causes steam_api.bundle to not get copied. Changing the target to intel64 solves this one.

**Comment by rlabrecque** [comment]
This Debug Info output could also be related:

https://github.com/rlabrecque/Steamworks.NET/blob/7d5c06394235361c5377f1b81c320218d74c7a50/Editor/Steamworks.NET/RedistCopy.cs#L67-L83

Specifically Line 70 was added because this code would sometimes get called before Unity created the Plugins folder.

This could be problematic when building on Windows for macOS, as Windows is case insensitive (by default), if Steamworks.NET creates the "Plugins" folder, then Unity tries to create "PlugIns" later, it will likely still end up as "Plugins".

For this piece of code we need to figure out the rules behind Plugins/PlugIns. Do we always use "PlugIns" in a certain version of Unity onward? Do we always use "PlugIns" just when building for macOS?

**Comment by TautvydasZilys** [comment]
> [Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.

If steam_api plugin is x64, and you're running on Apple silicon device natively, you won't be able to load it.

> macOS Plugins -> PlugIns change causes steam_api.bundle not to get copied.

This change did not affect how plugins were copied. It was literally a change in the string literal for the target folder. What's more likely happening is that if a plugin is configured to be only compatible with `Intel 64-bit` builds, and you're building `Intel 64-bit + Apple Silicon`, it will not get copied because it's not "compatible" with your current build target.

> Plugins/x86_64/libsteam_api.so gets incorrectly copied on macOS, possibly causes a conflict with steam_api.bundle.

This is a bug in Unity. It will not cause conflicts for loading the plugin, but it should not be copied. It would be great if you could file a bug report on this.

> Building from an Apple Silicon Mac results in a broken build (unknown why as of yet).

Broken how?

> Given this folder layout: https://github.com/rlabrecque/Steamworks.NET/tree/master/Plugins are there any obvious problems, or should I open a ticket?

That layout looks fine. The .so file getting copied is a bug. Generally though, we advice committing the meta files into the repository: they contain richer configuration information and are not dependent on a folder name. When Unity doesn't find a .meta file next to a file that is a plugin, it will run the "plugin importer" process, look at the file layout and create .meta files according to the default settings for the folder names. Once that is done, folder names don't matter any more and Unity will not look at them ever again.

> Specifically Line 70 was added because this code would sometimes get called before Unity created the Plugins folder.

I don't think that could be the case. `OnPostprocessBuild` callback gets called at the very end of the build, after Unity did everything it will ever do to that build.

> Do I need to rename this Plugins folder for the steam_api.bundle copy to work for modern macOS, or does Unity do that automatically?

Unity will do it for you. It does not copy the Plugins folder, just individual plugins.

> For this piece of code we need to figure out the rules behind Plugins/PlugIns. Do we always use "PlugIns" in a certain version of Unity onward? Do we always use "PlugIns" just when building for macOS?

I would check for the folder existence and if it doesn't exist, throw an exception. Something went wrong with the build: if Unity didn't copy those files, they were either configured incorrectly, or something else went wrong. You shouldn't ever hit that.

**Comment by TautvydasZilys** [comment]
On a related note, where does `steam_api.bundle` come from? The solution to all these problems is have that .bundle recompiled to be a fat bundle, so it could be run on both Intel 64-bit and Apple silicon Macs.

**Comment by buddhisthead** [comment]
Update: I really appreciate the detailed descriptions offered here by @TautvydasZilys and @rlabrecque
Based on the discussion, I built the app from an M1 Mac and changed the Steam_api.bundle CPU setting, under the player tab, to "Any CPU" and then set the Architecture in the Build Settings (for PC, Mac & Linux Standalone) to "Intel 64-bit" with Target Platform set as "macOS". A build with these settings does correctly run on the M1 Mac. Awesome!

![Screen Shot 2021-01-21 at 9 00 51 AM](https://user-images.githubusercontent.com/1738802/105385422-307cbc80-5bc8-11eb-9b0e-0bb0432927b9.png)

![Screen Shot 2021-01-21 at 9 01 26 AM](https://user-images.githubusercontent.com/1738802/105385432-34a8da00-5bc8-11eb-84e7-c1afefb08d13.png)

And for completeness, I tested again the configuration that does NOT run (i.e. steam api lib/bundle not found at startup). Changing the Build Settings Architecture to "Intel 64-bit + Apple Silicon" will fail on startup. All other settings remain as described above.

I think this does make the case for building a fat bundle that has both slices for Intel 64-bit and Apple Silicon. I have written build scripts for making fat frameworks and am happy to help if I can learn more about where steam bundle gets built.

**Comment by rlabrecque** [comment]
> This is a bug in Unity. It will not cause conflicts for loading the plugin, but it should not be copied. It would be great if you could file a bug report on this.

💯 Will do! Agreed after more info it seems benign, just unnecessary and is potential confusion.

> That layout looks fine. The .so file getting copied is a bug. Generally though, we advice committing the meta files into the repository: they contain richer configuration information and are not dependent on a folder name. When Unity doesn't find a .meta file next to a file that is a plugin, it will run the "plugin importer" process, look at the file layout and create .meta files according to the default settings for the folder names. Once that is done, folder names don't matter any more and Unity will not look at them ever again.

This seems like the easiest/most impactful task I could do for this. I forget why I didn't include them originally, but I know it's been asked for for other reasons as well.

> On a related note, where does steam_api.bundle come from? The solution to all these problems is have that .bundle recompiled to be a fat bundle, so it could be run on both Intel 64-bit and Apple silicon Macs.

That comes from Valve unfortunately. I'll poke them to see if there's any immediate plans for that as well!

**Comment by wagenheimer** [comment]
Is this still not fixed? I have to manually copy steam_api.bundle to the build folder for MacOs Build on UInity 2020.3.4f1

**Comment by rlabrecque** [comment]
This should be fixed as of https://github.com/rlabrecque/Steamworks.NET/pull/414 on the master branch, hasn't made it's way into a release quite yet though.
