### ISSUE TITLE
After steam_init success, steam not launch GameOverlayUI.exe, steam overlay UI not work.

### ISSUE THREAD

**Issue by gqw** [rlabrecque/Steamworks.NET#394]
Today, I found After call steam_init(SteamManager.Awake) success, steam not launch GameOverlayUI.exe, steam overlay UI not work,  but yesterday everything is ok.

1. I can active game's steam overlay ui through steam launcer, or use steam://open
2. When I run my game with "Build and Run", it will be failed to see steam overlay ui.
3.  When I laucher game with double click my game execution file(with steam_appid.txt),  it failed too.
4.  I add log at the end of SteamManager.Awake function, log shows init is ok.
5. And through steam client console(steam://open/console), I can see the log infomation:
----
Starting app 480
>>> Adding process 24024 for game ID 480
Game removed: AppID 480 "", ProcID 24024 
Exiting app 480
----
That means they're communicating(steam launcher and game).
6. I even move the init work to below code, but failed too:
```c#
public class FirstClass
{
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    static void OnBeforeSceneLoadRuntimeMethod()
    {
        //if (SteamManager.Initialized)
        //{
        //    Debug.Log("SteamManager.Initialized");
        //}
        Debug.Log("Before first Scene loaded");
    }

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
    static void OnAfterSceneLoadRuntimeMethod()
    {
        Debug.Log("After first Scene loaded");
    }

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSplashScreen)]
    static void OnBeforeSplashScreenMethod()
    {
        if (SteamManager.Initialized)
        {
            Debug.Log("SteamManager.Initialized");
        }
        Debug.Log("OnBeforeSplashScreenMethod loaded");
    }

    [RuntimeInitializeOnLoadMethod]
    static void OnRuntimeMethodLoad()
    {
        Debug.Log("RuntimeMethodLoad: After first Scene loaded");
    }
}
```
7. I write a demo with c++(very simple, just call steam_init()), it's ok, and can show the steam overlay UI.

----

Steam version: 6.28.18.86
Unity version: 

>m_EditorVersion: 2020.2.1f1
>m_EditorVersionWithRevision: 2020.2.1f1 (270dd8c3da1c)

Steamwork.net version: Steamworks.NET_14.0.0.unitypackage

**Comment by rlabrecque** [comment]
Hey @gqw I believe this is a result of Steam_API.Init() getting called after the renderer is initialized. With Unity this happens most of the time. (Exception being in the editor because new windows are being created all the time.)

But this generally should not be a problem in packaged builds you release because SteamAPI_RestartAppIfNecessary should be restarting your game through the steam launcher with `steam://open` when launched from the exe directory. In that case as you've found Steam will inject the overlay before any Unity code runs so the overlay will be injected correctly.

It may also be useful to look at these two log files:

- C:\Program Files (x86)\Steam\GameOverlayRenderer.log
- C:\Program Files (x86)\Steam\GameOverlayUI.exe.log

In theory there may be ways to run this code pre-renderer init, but in practice it's not that easy, especially as we look
