### ISSUE TITLE
A Compiler Directive for Enabling Steamworks.Net

### ISSUE THREAD

**Issue by khatamnejad** [rlabrecque/Steamworks.NET#412]
I think it would be better and user-friendlier to compile the Streamworks.Net files only when a directive (like `STEAMWORKS`) is present. At the moment things are a bit hard and unnatural for me since Steam is not necessarily my only PC/Standalone target and in order to compile the game for another platform - say Epic - I have to add `DISABLESTEAMWORKS` symbol to the player's setting; While this works it is not very logical and natural and also it ties my setting to the internal implementation of Steamworks.Net library which is not necessarily going to stay this way and also it is not guaranteed that all the files in the library using the same logic.

I think it would be user-friendlier to me if I could **enable** the Steamworks.Net library in the settings using a general directive like `STEAMWORKS` instead of **disabling** it using `DISABLESTEAMWORKS` directive.

P.S. I had to change the title and description since my understanding of the design improved.

**Comment by rlabrecque** [comment]
The problem here is that we want a good out of the box experience, in that it should just work without any real human input. Restricting the scope ends up being a little more advanced.

I wonder if the Unity Package Manager version helps at all?

https://github.com/rlabrecque/Steamworks.NET/pull/414

I believe you could have builds where it's included when you include a package with your Steam logic in it.
