### ISSUE TITLE
SteamAPI.Shutdown not working

### ISSUE THREAD

**Issue by valentin56610** [rlabrecque/Steamworks.NET#466]
Hello guys !

I have just upgraded to the 20.0 version of Steamworks.NET and I can notice the following issue : Game never closes.
I mean when I run the game through steam and close it, Steam says it's still running, and pressing the quit button of the game makes the game freeze
Was working fine before I upgraded, all the rest is fine as well, really just shutting down the API doesn't work

I have tested this on MacOS with an M1 model, don't have access to anything else, don't know if the issue happens on other platforms 

I have my SteamAPI.Shutdown(); call in the private void OnApplicationQuit() method

Cheers !

EDIT : It's making my CPU heat up a lot, even if the game is closed
EDIT 2 : Can't open the game anymore through Steam, it stays at the bottom and can't close it at all even through force quit
EDIT 3 : I reverted back to previous version of Steamworks.NET, deleting everything from the new version, and even with that the game still freezes. I don't know how but 20.0 destroyed absolutely everything :(

**Comment by JamesMcGhee** [comment]
If you have reverted then 20.0 isn't in play anymore

So either v20 has some issue and you didn't fully revert 
or
The issue is not related to v20

So lets see if your fully reverted.

### Source Control
1st I am assuming you do not use source control so you cant simply revert by using your source control?
I would realyl quite strongly recomend you add source control to your project ... personally I hate Git but some love it. Unity's Collab is supper easy to use, little slow but easy to use, Plastic SCM has a cost but is very robust.

### Manual Removal
Setting source control aside

If your using Package Manager removing is really easy just press the Uninstall but I am assuming your using the downloaded unity package. 

1. Make sure your deleted all of its parts. Its prety common to forget to remove the Editor and Plugins folders
2. Once you have removed that, close Unity, your IDE, Steam client and anything else that might have any of it mounted. 
3. Clear out your Library and Temp folders. Restart Unity it will rebuild all of that. Note that this isn't always needed but if yoru suspect that Unity is holding onto something then do it.
4. Then reimport whatever version it is your after

If you do that and your still having this issue then it cannot be due to Steamworks.NET v20 since that is defently not there anymore.

**Comment by valentin56610** [comment]
I don’t know what happened I completely removed it then changed my computer and decided to work on it again and it all worked
So … working fine now!
