### ISSUE TITLE
Why not include SteamManager in Version 20.0 anymore?

### ISSUE THREAD

**Issue by sdw283074970** [rlabrecque/Steamworks.NET#478]
SteamManager turns to optional in Version 20.0 but the Steamworks.NET still depends on it. I have to download SteamManager manually, which is conflicts with the installation instruction that said the SteamManager is Optional.

**Comment by rlabrecque** [comment]
Hey there, I just checked and the .unitypackage version of Steamworks.NET does still include the SteamManager script:

![image](https://user-images.githubusercontent.com/2047188/150704755-19c6e960-6f11-429d-b01b-27908e45a4b8.png)

SteamManager has always been optional though, as it's technically user-code and is outside of the core scope of Steamworks.NET. Users will likely want to opt to not use it if they already have some abstraction for handling platform systems, and would probably rather wrap even the Steamworks initialization logic in that.

We can't ship it with the unity package manager version because being user code you basically HAVE to make modifications to it, at the very least to replace the AppId in RestartAppIfNecessary.

I can clarify the wording to say something like "Recommended but optional:" if that helps? And probably providing a bit more of this context on this page: http://steamworks.github.io/steammanager/
