### ISSUE TITLE
Steam DLLs missing from NuGet package 20.1.0?

### ISSUE THREAD

**Issue by cove** [rlabrecque/Steamworks.NET#493]
When I try to call `SteamEncryptedAppTicket.BDecryptTicket()` I get an error that it can't find the Steam DLL:
```
      System.DllNotFoundException: Unable to load DLL 'sdkencryptedappticket64' or one of its dependencies: The specified module could not be found. (0x8007007E)
         at Steamworks.NativeMethods.SteamEncryptedAppTicket_BDecryptTicket(Byte[] rgubTicketEncrypted, UInt32 cubTicketEncrypted, Byte[] rgubTicketDecrypted, UInt32& pcubTicketDecrypted, Byte[] rgubKey, Int32 cubKey)
         at Steamworks.SteamEncryptedAppTicket.BDecryptTicket(Byte[] rgubTicketEncrypted, UInt32 cubTicketEncrypted, Byte[] rgubTicketDecrypted, UInt32& pcubTicketDecrypted, Byte[] rgubKey, Int32 cubKey)
...
```

And looking in the nuget dir I also don't see any Steam DLLs:

```
C:\Users\covec\.nuget\packages\steamworks.net\20.1.0>dir /s |findstr "dll"
02/25/2022  08:27           375,296 Steamworks.NET.dll
02/25/2022  08:27           375,296 Steamworks.NET.dll
02/25/2022  08:27           375,296 Steamworks.NET.dll
02/25/2022  08:27           375,808 Steamworks.NET.dll
02/25/2022  08:27           375,296 Steamworks.NET.dll
02/25/2022  08:27           375,808 Steamworks.NET.dll
02/25/2022  08:34           375,296 Steamworks.NET.dll
02/25/2022  08:27           375,808 Steamworks.NET.dll
```

This is the first time I've tried the nuget package, should I be using the standalone version instead?

**Comment by rlabrecque** [comment]
Hey @cove, The [sdkencryptedappticket64.dll](https://github.com/rlabrecque/SteamworksSDK/blob/main/public/steam/lib/win64/sdkencryptedappticket64.dll)'s arent distributed by default because 99.99% of people don't need them, but you can just download the ones from the same version of the Steamworks SDK that the version of Steamworks.NET you're using is compatible with.

I believe this should be documented in the documentation as well

**Comment by cove** [comment]
Hey @rlabrecque, yeah makes sense. Thanks!
