### ISSUE TITLE
SteamUser interface is missing GetAuthTicketForWebApi

### ISSUE THREAD

**Issue by Ash-oi** [rlabrecque/Steamworks.NET#549]
is this on a newer SDK version or something?

https://partner.steamgames.com/doc/api/ISteamUser#GetAuthTicketForWebApi

**Comment by CodingDaniel1** [comment]
Hello, im also issuing with this, ive tried to implement it myself, just like how the steamworks.NET dev did, but it turns out i cant receive a callback [GetTicketForWebApiResponse_t], the [SteamUser.GetAuthTicketForWebApi] works perfectly fine and returns value 1, but i just cant receive the callback

**Comment by WongKit** [comment]
Same here. The GetAuthTicketForWebApi is the only function I was planning to use. It looks like, the embedded steam_api.dll does not contain this interface either.

**Comment by rlabrecque** [comment]
I haven't had a chance to look into this much but it looks like this was fixed with #553 ?

GetAuthTicketForWebApi seems like a new function in 1.57
