### ISSUE TITLE
Steam P2P messages are delayed by almost 60 seconds

### ISSUE THREAD

**Issue by BrickmadeProductions** [rlabrecque/Steamworks.NET#595]
I recently just got my godot game setup with multiplayer, using steamworks.net p2p for syncing position information. I have the 

OnP2PRequestCallback(P2PSessionRequest_t request) callback setup, with 

SteamNetworking.AcceptP2PSessionWithUser(request.m_steamIDRemote); inside the callback. 

I am sending position data every frame, and I am receiving position data every frame (I have prints on both ends) but for some reason it takes almost a minute for the data coming in to change to what it was 1 minute ago on the opposing user's client. I genuinely have no clue why this would happen, its such a weird bug I have no idea how to even approach it. This has been reproduced with a testing computer I have on my network as well as a friend's computer. (both being connected p2p to my computer). I have also confirmed the connections and both clients have a valid session with eachother. Any Ideas?

**Comment by Idles** [comment]
The Steam [APIs you're using](https://partner.steamgames.com/doc/api/ISteamNetworking) are deprecated and shouldn't be used for new projects. You should build on the newer P2P APIs like `ISteamNetworkingSockets` or `ISteamNetworkingMessages`. 

If you have other usage problems (that aren't clearly caused by Steamworks.NET), you'll have much more luck getting answers in the official [Steamworks discussion board](https://steamcommunity.com/groups/steamworks/discussions/)
