### ISSUE TITLE
SteamGameServer.InitGameServer() causes crash

### ISSUE THREAD

**Issue by DetectiveMittens** [rlabrecque/Steamworks.NET#60]
Hi, I'm really struggling to register my game servers on the Steam masterserver. In the example repo they just call SteamGameServer.ServerRules() or something, but when I do this, it always calls to failure callback. I tried to research how to correctly register a server and found other games calling SteamGameServer_Init().
So I tried this code in my project

if (SteamManager.Initialized) {
     bool success = SteamGameServer.InitGameServer( ip_uint, serverPort, queryPort, 3, new AppId_t(395080), game_version);
     Debug.LogWarning("InitGameServer reutrned "+success);
}

But every time it runs Unity will crash.
I also tried using GameServer.InitSafe() but this just always returns false

**Comment by DetectiveMittens** [comment]
After restarting my computer it's stopped crashing, Instead I get this error thrown in the unity log "Steamworks is not initialized."

I realize there are many functions which throw that error, so the log says this particular one is coming out of 

public static void TestIfAvailableGameServer() {
			TestIfPlatformSupported();
			if (NativeMethods.SteamClientGameServer() == System.IntPtr.Zero) {
				throw new System.InvalidOperationException("Steamworks is not initialized.");
			}
		}

inside InteropHelp.cs

**Comment by DetectiveMittens** [comment]
So, given the condition for the error to get thrown, my problem is more specifically that NativeMethods.SteamClientGameServer() is always returning as System.IntPtr.Zero.
What causes this? What does it mean?

**Comment by rlabrecque** [comment]
Hey @DetectiveMittens, A little oddity with Steamworks.NET is that the SteamGameServer_*() exported functions like Steam had to be renamed because the collided with the SteamGameServer interface.

So SteamGameServer_Init() just ends up being Steamworks.GameServer.Init();

The SteamGameServer interface is available after successfully calling SteamAPI.Init() or GameServer.Init().

So "Steamworks is not initialized" should be pretty normal if that's the first thing you're trying to call.


So finding out why GameServer.Init is returning false is the first step. I'm not really sure of all the conditions where that happens.

This is the args that I used when I last tried it out:
bool ret = GameServer.Init(0, 8766, 27015, 27016, EServerMode.eServerModeNoAuthentication, "1.0.0.0");

Is steam running?

**Comment by DetectiveMittens** [comment]
Like you said GameServer.Init() always returns false, 
Yes, Steam is definitely running. I'm able to pull in my Steam ID and Steam persona name successfully right before trying to Init the game server. 

Maybe I need to shutdown the normal steam API before trying to Init the game server API?

**Comment by DetectiveMittens** [comment]
Nope, calling SteamAPI.Shutdown() before trying to Init the GameServer API doesn't seem to make any difference :(

**Comment by DetectiveMittens** [comment]
@rlabrecque I've made some progress, but I need your input on this.
![steamworksmasterserver1](https://cloud.githubusercontent.com/assets/8984206/9459756/5315b54a-4b42-11e5-92ef-3bc16bd88a99.jpg)

**Comment by rlabrecque** [comment]
Have Valve enabled your game to show up in the internet server browser yet? That's something that they need to do on their end.

**Comment by DetectiveMittens** [comment]
I got it all to register by adding SteamGameServer.ForceHeartbeat(); At the end of the function!
