### ISSUE TITLE
SteamAPI_InitFlat

### ISSUE THREAD

**Issue by JB0xc390cc** [rlabrecque/Steamworks.NET#643]
This method doesn't get parsed/generated into C# files.
Is there any reason for this or just a bug?
It'll be important though? look what the comments says:
https://github.com/rlabrecque/Steamworks.NET/blob/a2fc889ab2672981ec3e6225d551d86ce6923121/CodeGen/steam/steam_api.h#L78

https://github.com/rlabrecque/Steamworks.NET/blob/a2fc889ab2672981ec3e6225d551d86ce6923121/CodeGen/steam/steam_api.h#L105

**Comment by rlabrecque** [comment]
We have more advanced mechanisms that allow us to call into the non-Flat version safely, since this project existed many years before the Flat APIs were introduced. We could include it in the NativeMethods if desired, but I'd probably just recommend using InitEx:

https://github.com/rlabrecque/Steamworks.NET/blob/master/com.rlabrecque.steamworks.net/Runtime/Steam.cs#L57

**Comment by JB0xc390cc** [comment]
thanks :)
