### ISSUE TITLE
Steam Overlay Problem

### ISSUE THREAD

**Issue by Eb42** [rlabrecque/Steamworks.NET#80]
Windows7,Unity 5.2.2

1) If I hit 'build and run', all is well and Shift+Tab brings up the overlay.

2) If I then double click the exact same .exe, Shift+Tab does nothing! The API still seems to be working as the messages on-screen are correct, but it's impossible to bring up the overlay.

I'm at a complete loss as to why "build and run" should be different from double clicking the exe. Any ideas?

3) If I upload build to Steam and run from Steam Client, Shift+Tab does nothing! 

But SteamAPI.Init() and SteamUser.GetSteamID() works well every time (1,2,3). Just overlay works only in case 2.

Any ideas?

**Comment by rlabrecque** [comment]
Hey, sorry for the super late reply, It's probably pretty pointless at this point but... the reason why the overlay doesn't come up when you run the exe directly is that the overlay only gets injected when you call SteamAPI.Init. For the overlay to be properly injected it must happen before D3D/OpenGL are initialized, which on Unity happens before scripts get run. When you build and run: If you have already injected the overlay into the Unity Editor with SteamAPI.Init then overlay automatically gets injected into the child process when it starts.

Ideally you should be calling SteamAPI.RestartAppIfNecessary() and quitting so that it relaunches through Steam which injects the overlay when the process is [re]created.
