### ISSUE TITLE
Issues with Unity 4.6.0f3

### ISSUE THREAD

**Issue by rkg-p-szczerbinski** [rlabrecque/Steamworks.NET#96]
Hi,

I am currently implementing fixes to a game that is made in Unity 4.6.0f3 but I am experiencing issues with the Steamworks.NET package. This problem only occurs when trying to play the game in the editor.

With the source of the game that was sent to me, when starting the game in the Editor, I am getting the following error:
`[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: PROJECTDIRECTORY/Assets/Plugins/x86/CSteamworks.dll
`

To confirm, the steam_api.dll is present in the directory where CSteamworks.dll is.

After looking through older issues, I have tried to update Steamworks.NET to the latest version but this caused another issue, where when pressing play in the editor, Unity will just crash. I used DbgView to try to get more information on the problem but all I got was this: http://pastebin.com/r4gvb088

Any ideas on what could be causing this?

Thanks.

**Comment by rlabrecque** [comment]
Sorry for the late reply, I hope you ended up getting this fixed!

But the issue is likely that the steam_api.dll isn't moved to the PROJECTDIRECTORY/ which needs to happen on Unity 4, It's supposed to automatically happen with editor scripts but maybe the project creators didn't keep those updated with Steamworks.NET itself or something like that.
